### ISSUE TITLE
学校视频看不了

### ISSUE THREAD

**Issue by yang55** [didanoDevelopers2017/didano-platform#2]
学校视频看不了，例如：
现象：学校id为11，班级为68，然后68班级的被删除了，新创建了一个591班级，两个班级名一样，但是591班级的家长看不了视频。
原因：原先的视频通道的配置是配置的68班（表vd_chennel）,新创建的班级591班没有视频通道的配置，家长进入看不到视频，而在超级管理后台配置视频，看到原来的视频配置变为了公共场所。
解决方案：1原始手动改变视频表的班级配置或者定期查看后台视频配置。2、开发程序进行控制

**Comment by stephenwang2017** [comment]
问题迁移
