### ISSUE TITLE
学生以及家长的后台导入

### ISSUE THREAD

**Issue by yang55** [didanoDevelopers2017/didano-platform#3]
现象：在导入中，会添加ic卡的信息，后台没有进行tb_ic_card表的修改
出错原因：在通讯录无法查询到ic卡号，导致修改学生的信息时卡号会被冲掉。
解决方案：如何是一条sql将所有的数据导入，将表中的rfid抽取出来进行修改ic卡表的学校改为要导入数据的学校。如果是一条一条的执行，就先修改ic卡表的学校，再将那条数据导入数据库中即可。

**Comment by stephenwang2017** [comment]
已经解决，关闭
